ST.UI.MVC/Areas/Yonetim/Controllers/AnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ST.UI.MVC.Areas.Yonetim.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnaController : Controller
    {
        // GET: Yonetim/Ana
        public ActionResult Index()
        {
            return View();
        }
    }
}

ST.UI.MVC/Controllers/AnaController.cs
using ST.BLL.Repository;
using System.Linq;
using System.Web.Mvc;
using ST.Models.ViewModels;
using ST.BLL.Settings;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;

namespace ST.UI.MVC.Controllers
{
    public class AnaController : Controller
    {
        // GET: Ana
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Restoranlar()
        {
            var model = new FirmaRepo().GetAll().Where(x => x.AktifMi)
                .Select(x => new FirmaViewModel()
                {
                    Id = x.Id,
                    Adres = x.Adres,
                    EklenmeTarihi = x.EklenmeTarihi,
                    FirmaAdi = x.FirmaAdi,
                    FirmaKapakFotoPath = x.FirmaKapakFotoPath,
                    FirmaProfilFotoPath = x.FirmaProfilFotoPath,
                    MinimumSiparisTutari = x.MinimumSiparisTutari,
                    OrtalamaTeslimSuresi = x.OrtalamaTeslimSuresi,
                    Telefon = x.Telefon
                })
                .OrderBy(x => x.MinimumSiparisTutari)
                .ThenBy(x => x.OrtalamaTeslimSuresi)
                .ToList();
            return View(model);
        }
        [AllowAnonymous]
        [Route("~/Aciktim/{baslik}-lokanta/{id?}")]
        public ActionResult Detay(int? id, string baslik)
        {
            if (id == null)
                return RedirectToAction("Restoranlar");

            var firma = new FirmaRepo().GetById(id.Value);
            if (firma == null)
                return RedirectToAction("Restoranlar");

            string basliktest = SiteSettings.UrlFormatConverter(firma.FirmaAdi);
            if (basliktest.ToLower() != baslik.ToLower())
                return RedirectToAction("Detay", new { id = firma.Id, baslik = basliktest });

            ViewBag.firmaid = firma.Id;
            //kategori
            //kategorinin ürünleri
            //firma bilgileri

            return View(firma);
        }
        public JsonResult FirmaninUrunleriniGetir(int id)
        {
            var firma = new FirmaRepo().GetById(id);
            if (firma == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Firma Bulunamadı"
                }, JsonRequestBehavior.AllowGet);
            }
            var urunmodel = new List<FirmaUrunKategoriViewModel>();
            new FirmaUrunRepo()
                .GetAll()
                .Where(x => x.SatistaMi = true && x.FirmaId == firma.Id)
                .ToList().ForEach(x =>
                    urunmodel.Add(new FirmaUrunKategoriViewModel
                    {
                        FiyatGorunum = $"{x.UrunFiyat:c2}",
                        Fiyat = x.UrunFiyat,
                        UrunId = x.UrunId,
                        UrunAdi = x.Urun.UrunAdi,
                        UrunResimPath = x.Urun.UrunFotografYolu,
                        KategoriAdi = x.Urun.UrunKategori.KategoriAdi,
                        KategoriAciklama = x.Urun.UrunKategori.Aciklama
                    })
                );


            var firmaUrunModel = new FirmaUrunleriViewModel()
            {
                Id = firma.Id,
                FirmaAdi = firma.FirmaAdi,
                MinimumSiparisTutari = firma.MinimumSiparisTutari,
                OrtalamaSiparisSuresi = firma.OrtalamaTeslimSuresi,
                Urunler = urunmodel.OrderBy(x => x.KategoriAdi).ToList()
            };


            var data = new
            {
                success = true,
                data = firmaUrunModel
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult OdemeTipleriniGetir()
        {
            var data = new OdemeTipiRepo().GetAll().Select(x => new { x.Id, x.OdemeTipiAdi }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize]
        public ActionResult SepetiOnayla(SepetViewModel model)
        {
            model.KullaniciId = HttpContext.User.Identity.GetUserId();
            new SiparisRepo().Insert(model);
            return RedirectToAction("Profilim", "Hesap");
        }
    }
}

ST.UI.MVC/Views/Ana/Detay.cshtml
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<div class="container m-t-30" ng-app="site" ng-controller="SepetCtrl" ng-cloak>
    <div style="display:none;">{{firmaid= @ViewBag.firmaid}}</div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9">
            <div class="menu-widget m-b-30" ng-repeat="(key,value) in data.Urunler| groupBy:'KategoriAdi'">
                <div class="widget-heading">
                    <h3 class="widget-title text-dark">
                        {{key}}<a class="btn btn-link pull-right" data-toggle="collapse" href="#popular" aria-expanded="true">
                            <i class="fa fa-angle-right pull-right"></i>
                            <i class="fa fa-angle-down pull-right"></i>
                        </a>
                    </h3>
                    <div class="clearfix"></div>
                </div>
                <div class="collapse in">
                    <div class="food-item" ng-repeat="urun in value">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-lg-8">
                                <div class="rest-logo pull-left">
                                    <a class="restaurant-logo pull-left" href="#"><img src="~/{{urun.UrunResimPath}}" alt="Food logo"></a>
                                </div>
                                <!-- end:Logo -->
                                <div class="rest-descr">
                                    <h6><a href="#">{{urun.UrunAdi}}</a></h6>
                                </div>
                                <!-- end:Description -->
                            </div>
                            <!-- end:col -->
                            <div class="col-xs-12 col-sm-12 col-lg-4 pull-right item-cart-info"> <span class="price pull-left">{{urun.FiyatGorunum}}</span> <a href="#" class="btn btn-small btn btn-secondary pull-right" data-toggle="modal" data-target="#order-modal" ng-click="sepeteekle(urun)">&#43;</a> </div>
                        </div>
                        <!-- end:row -->
                    </div>
                    <!-- end:Food item -->
                </div>
                <!-- end:Collapse -->
            </div>
            <!-- end:Widget menu -->
            <div class="row m-t-30">
                <div class="col-sm-12 col-xs-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" class="panel-toggle collapsed" href="#faq1" aria-expanded="false">Can I viverra sit amet quam eget lacinia?</a></h4>
                        </div>
                        <div class="panel-collapse collapse" id="faq1" aria-expanded="false" role="article" style="height: 0px;">
                            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rutrum ut erat a ultricies. Phasellus non auctor nisi, id aliquet lectus. Vestibulum libero eros, aliquet at tempus ut, scelerisque sit amet nunc. Vivamus id porta neque, in pulvinar ipsum. Vestibulum sit amet quam sem. Pellentesque accumsan consequat venenatis. Pellentesque sit amet justo dictum, interdum odio non, dictum nisi. Fusce sit amet turpis eget nibh elementum sagittis. Nunc consequat lacinia purus, in consequat neque consequat id.</div>
                        </div>
                    </div>
                    <!--//panel-->
                    <div class="panel">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" class="panel-toggle" href="#faq2"><i class="ti-info-alt"></i>What is the ipsum dolor sit amet quam tortor?</a></h4>
                        </div>
                        <div class="panel-collapse collapse" id="faq2">
                            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rutrum ut erat a ultricies. Phasellus non auctor nisi, id aliquet lectus. Vestibulum libero eros, aliquet at tempus ut, scelerisque sit amet nunc. Vivamus id porta neque, in pulvinar ipsum. Vestibulum sit amet quam sem. Pellentesque accumsan consequat venenatis. Pellentesque sit amet justo dictum, interdum odio non, dictum nisi. Fusce sit amet turpis eget nibh elementum sagittis. Nunc consequat lacinia purus, in consequat neque consequat id.</div>
                        </div>
                    </div>
                    <!--//panel-->
                    <div class="panel">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" class="panel-toggle" href="#faq3"><i class="ti-info-alt"></i>How does lorem ipsum work?</a></h4>
                        </div>
                        <div class="panel-collapse collapse" id="faq3">
                            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rutrum ut erat a ultricies. Phasellus non auctor nisi, id aliquet lectus. Vestibulum libero eros, aliquet at tempus ut, scelerisque sit amet nunc. Vivamus id porta neque, in pulvinar ipsum. Vestibulum sit amet quam sem. Pellentesque accumsan consequat venenatis. Pellentesque sit amet justo dictum, interdum odio non, dictum nisi. Fusce sit amet turpis eget nibh elementum sagittis. Nunc consequat lacinia purus, in consequat neque consequat id.</div>
                        </div>
                    </div>
                    <!--//panel-->
                    <div class="panel">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" class="panel-toggle" href="#faq4"><i class="ti-info-alt"></i>Can I ipsum dolor sit amet nascetur ridiculus?</a></h4>
                        </div>
                        <div class="panel-collapse collapse" id="faq4">
                            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rutrum ut erat a ultricies. Phasellus non auctor nisi, id aliquet lectus. Vestibulum libero eros, aliquet at tempus ut, scelerisque sit amet nunc. Vivamus id porta neque, in pulvinar ipsum. Vestibulum sit amet quam sem. Pellentesque accumsan consequat venenatis. Pellentesque sit amet justo dictum, interdum odio non, dictum nisi. Fusce sit amet turpis eget nibh elementum sagittis. Nunc consequat lacinia purus, in consequat neque consequat id.</div>
                        </div>
                    </div>
                    <!--//panel-->
                </div>
            </div>
            <!--/row -->
        </div>
        <!-- end:Bar -->
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
            <div class="sidebar-wrap">
                <div class="widget widget-cart">
                    <div class="widget-heading">
                        <h3 class="widget-title text-dark">
                            Sepetiniz
                        </h3>
                        <div class="clearfix"></div>
                    </div>
                    <div class="order-row bg-white" ng-repeat="urun in sepet">
                        <div class="widget-body">
                            <div class="title-row">
                                {{urun.UrunAdi}}
                                <a href="#" ng-click="sepettencikart(urun)"><i class="fa fa-trash pull-right"></i></a>
                            </div>
                            <div class="form-group row no-gutter">
                                <div class="col-xs-12">
                                    <input class="form-control" step="1" type="number" ng-model="urun.Adet" ng-change="adetarttir(urun)">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- end:Order row -->
                    <div class="widget-delivery clearfix">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 b-t-0">
                            <md-switch ng-model="hemenmi" aria-label="Switch 1">
                                <div ng-show="hemenmi" class="label">
                                    Hemen(~{{data.OrtalamaSiparisSuresi}} dk.)
                                </div>
                                <div ng-show="!hemenmi" class="label">
                                    İleri Tarih
                                </div>
                            </md-switch>
                        </div>
                        <div ng-if="!hemenmi" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 b-t-0">
                            <input type="date" ng-model="zaman.tarih" class="form-control" /><br />
                            <input type="time" ng-model="zaman.saat" class="form-control" />
                        </div>
                        <div ng-show="sepettutari>=minimumsiparistutari" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 b-t-0">
                            <md-input-container class="md-block" flex-gt-sm>
                                <label>Ödeme Tipi</label>
                                <md-select ng-model="odemetipi">
                                    <md-option ng-repeat="tip in odemetipleri" value="{{tip.Id}}" >
                                        {{tip.OdemeTipiAdi}}
                                    </md-option>
                                </md-select>
                            </md-input-container>
                        </div>
                    </div>
                    <div class="widget-body">
                        <div class="price-wrap text-xs-center">
                            <p>Toplam</p>
                            <h3 class="value"><strong>{{sepettutari}} ₺</strong></h3>
                            <div ng-if="sepettutari<minimumsiparistutari">
                                <span class="text text-danger">Sipaiş verebilmeniz için sepetinize {{minimumsiparistutari-sepettutari}}₺ kadar ürün eklemelisiniz</span>
                            </div>
                            <input type="button" ng-show="sepettutari>=minimumsiparistutari" class="btn theme-btn btn-lg" value="Sipariş Ver" ng-click="sepetionayla()" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end:Right Sidebar -->
    </div>
    <!-- end:row -->
</div>

ST.UI.MVC/Views/Ana/Index.cshtml
@{
    ViewBag.Title = "Ana Sayfa";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Index</h2>

@HttpContext.Current.User.Identity.GetUserName()

ST.UI.MVC/Views/Ana/Restoranlar.cshtml
@model List<FirmaViewModel>
@{
    ViewBag.Title = "Restoranlar";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<div class="top-links">
    <div class="container">
        <ul class="row links">
            <li class="col-xs-12 col-sm-3 link-item active"><span>1</span><a href="restaurants.html">Restorant Seç</a></li>
            <li class="col-xs-12 col-sm-3 link-item"><span>2</span><a href="profile.html">Yemeğini Seç</a></li>
            <li class="col-xs-12 col-sm-3 link-item"><span>3</span><a href="checkout.html">Ödemeni Yap</a></li>
        </ul>
    </div>
</div>
<!-- end:Top links -->
<!-- start: Inner page hero -->
<div class="inner-page-hero bg-image" data-image-src="http://placehold.it/1670x480">
    <div class="container"> </div>
    <!-- end:Container -->
</div>
<div class="restaurant-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @foreach (var item in Model)
                {
                    <div class="bg-gray restaurant-entry">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-8 text-xs-center text-sm-left">
                                <div class="entry-logo">
                                    <a class="img-fluid" href="#">
                                        <img src="@(string.IsNullOrEmpty(item.FirmaProfilFotoPath)?"http://placehold.it/110x110":"../"+item.FirmaProfilFotoPath)" alt="Food logo">
                                    </a>
                                </div>
                                <!-- end:Logo -->
                                <div class="entry-dscr">
                                    <h5><a href="#">@item.FirmaAdi</a></h5> <span>
                                        @item.Adres<a href="#">...</a>
                                    </span>
                                    <ul class="list-inline">
                                        <li class="list-inline-item"><i class="fa fa-check"></i> @($"{item.MinimumSiparisTutari:c2} En az")</li>
                                        <li class="list-inline-item"><i class="fa fa-motorcycle"></i> @($"{item.OrtalamaTeslimSuresi} dk.")</li>
                                    </ul>
                                </div>
                                <!-- end:Entry description -->
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-4 text-xs-center">
                                <div class="right-content bg-white">
                                    <div class="right-review">
                                        <div class="rating-block"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> </div>
                                        <p> 245 Reviews</p> <a href="@Url.Action("Detay", "Ana", new { id = item.Id, baslik = ST.BLL.Settings.SiteSettings.UrlFormatConverter(item.FirmaAdi) })" class="btn theme-btn-dash">
                                        Firmayı seç</a>
                                    </div>
                                </div>
                                <!-- end:right info -->
                            </div>
                        </div>
                        <!--end:row -->
                    </div>
                <!-- end:Restaurant entry -->
                }

            </div>
        </div>
    </div>
</div>